FROM golang:1.19.2-alpine3.16 as builder

WORKDIR /app

COPY . .

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o consumer -ldflags="-w -s" ./cmd/consumer/main.go

#############

FROM scratch

COPY --from=builder /app/consumer /consumer

CMD [ "/consumer" ]